const authors = [
  {
    name: "Emma Thompson",
    designation: "Senior Content Writer @WriteWell",
    facebook: "https://facebook.com/emmathompsonwrites",
    twitter: "https://twitter.com/EmmaT_Writes",
    instagram: "https://instagram.com/emmathompson.author",
    linkedin: "https://linkedin.com/in/emmathompson",
    image: "/Resources/aboutUs/Author1.png",
  },
  {
    name: "Liam Carter",
    designation: "Lead Copywriter @StoryCraft",
    facebook: "https://facebook.com/liamcartercopy",
    twitter: "https://twitter.com/LiamC_Words",
    instagram: "https://instagram.com/liamcarterwrites",
    linkedin: "https://linkedin.com/in/liamcarter",
    image: "/Resources/aboutUs/Author2.png",
  },
  {
    name: "Sophia Nguyen",
    designation: "Content Strategist @NarrativeHub",
    facebook: "https://facebook.com/sophianguyencontent",
    twitter: "https://twitter.com/SophiaN_Stories",
    instagram: "https://instagram.com/sophianguyenwrites",
    linkedin: "https://linkedin.com/in/sophianguyen",
    image: "/Resources/aboutUs/Author3.png",
  },
  {
    name: "Noah Patel",
    designation: "Freelance Writer @PenPulse",
    facebook: "https://facebook.com/noahpatelwrites",
    twitter: "https://twitter.com/NoahP_Writer",
    instagram: "https://instagram.com/noahpatel.author",
    linkedin: "https://linkedin.com/in/noahpatel",
    image: "/Resources/aboutUs/Author4.png",
  },
  {
    name: "Olivia Kim",
    designation: "Editor-in-Chief @WordWave",
    facebook: "https://facebook.com/oliviakimedits",
    twitter: "https://twitter.com/OliviaK_Editor",
    instagram: "https://instagram.com/oliviakimwrites",
    linkedin: "https://linkedin.com/in/oliviakim",
    image: "/Resources/aboutUs/Author5.png",
  },
  {
    name: "Ethan Brooks",
    designation: "Content Manager @TaleTellers",
    facebook: "https://facebook.com/ethanbrookswrites",
    twitter: "https://twitter.com/EthanB_Content",
    instagram: "https://instagram.com/ethanbrooksauth",
    linkedin: "https://linkedin.com/in/ethanbrooks",
    image: "/Resources/aboutUs/Author6.png",
  },
  {
    name: "Ava Martinez",
    designation: "Creative Writer @InkVibe",
    facebook: "https://facebook.com/avamartinezwrites",
    twitter: "https://twitter.com/AvaM_Creates",
    instagram: "https://instagram.com/avamartinez.author",
    linkedin: "https://linkedin.com/in/avamartinez",
    image: "/Resources/aboutUs/Author7.png",
  },
  {
    name: "Mason Lee",
    designation: "Digital Content Specialist @ScriptSphere",
    facebook: "https://facebook.com/masonleewrites",
    twitter: "https://twitter.com/MasonL_Writer",
    instagram: "https://instagram.com/masonleewrites",
    linkedin: "https://linkedin.com/in/masonlee",
    image: "/Resources/aboutUs/Author8.png",
  },
];

export default authors;
